CREATE TYPE role AS ENUM ('user', 'admin', 'superadmin');

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  user_uid UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
  username VARCHAR(250) NOT NULL UNIQUE,
  email VARCHAR(300) NOT NULL UNIQUE,
  password VARCHAR(300) NOT NULL,
  user_role role NOT NULL,
  image_uri VARCHAR(300) UNIQUE,
  confirmed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);